//! Generate `src/rules_data.rs`, the research and diplomacy rules the game
//! hard-codes (the same approach as the combat factors in `src/combat.rs`:
//! the table lives in the source, a corpus-skipping test checks it against
//! the file).
//!
//! ```text
//! cargo run --release --manifest-path biq/Cargo.toml --example gen_game_rules \
//!     -- civ3/civ3-gog/app/Conquests/conquests.biq > src/rules_data.rs
//! ```
use civ3_biq::Biq;
use std::fmt::Write as _;
use std::process::ExitCode;

/// The civilizations the game plays, as `RACE.civilization_name` values.
const CIVS: [&str; 4] = ["Japan", "Rome", "Egypt", "China"];

/// The productions the game has, and the `PRTO`/`BLDG` name each maps to.
const UNITS: [&str; 7] = ["Warrior", "Archer", "Spearman", "Horseman", "Scout", "Settler", "Worker"];
const BLDGS: [&str; 3] = ["Barracks", "Granary", "Temple"];

fn q(s: &str) -> String {
    format!("{s:?}")
}

fn main() -> ExitCode {
    let Some(path) = std::env::args().nth(1) else {
        eprintln!("usage: gen_game_rules conquests.biq > src/rules_data.rs");
        return ExitCode::from(2);
    };
    let biq = match Biq::read_file(&path) {
        Ok(b) => b,
        Err(e) => {
            eprintln!("{path}: {e}");
            return ExitCode::from(1);
        }
    };
    let r = &biq.rules;
    let mut o = String::new();
    let w = &mut o;
    macro_rules! p {
        ($($a:tt)*) => { writeln!(w, $($a)*).unwrap() };
    }

    p!("//! Research and diplomacy rules of `conquests.biq`, hard-coded.");
    p!("//!");
    p!("//! @generated by `biq/examples/gen_game_rules.rs`; do not edit by hand.");
    p!("//! `tests::techs_match_the_biq` (here) re-reads the file and compares every");
    p!("//! advance when the game install is present; the other tables are checked by");
    p!("//! re-running the generator and diffing.");
    p!("#![allow(clippy::type_complexity)]");
    p!("");
    p!("use civ3mapgen::research::{{Rules, TechRow}};");
    p!("use civ3mapgen::research_ai::{{BldgRow, Tables, UnitRow}};");
    p!("");

    // --- advances -----------------------------------------------------------
    p!("/// Name of every advance, in `TECH` order.");
    p!("pub const TECH_NAMES: [&str; {}] = [", r.techs.len());
    for t in &r.techs {
        p!("    {},", q(&t.name.text()));
    }
    p!("];");
    p!("");
    p!("/// `(cost, era, prerequisites, flags, flavors)` of every advance.");
    p!("const TECHS: [(i32, i32, [i32; 4], u32, u32); {}] = [", r.techs.len());
    for t in &r.techs {
        p!(
            "    ({}, {}, {:?}, {:#x}, {:#x}),",
            t.cost,
            t.era,
            t.prerequisites,
            t.flags,
            t.flavors
        );
    }
    p!("];");
    p!("");
    let g = &r.general_rules[0];
    p!("/// `RULE` future technology cost.");
    p!("pub const FUTURE_TECH_COST: i32 = {};", g.future_tech_cost);
    p!("/// `RULE` maximum research time.");
    p!("pub const MAX_RESEARCH_TIME: i32 = {};", g.max_research_time);
    p!("/// `RULE` minimum research time.");
    p!("pub const MIN_RESEARCH_TIME: i32 = {};", g.min_research_time);
    p!("");
    p!("/// `ERAS` names.");
    p!("pub const ERA_NAMES: [&str; {}] = [", r.eras.len());
    for e in &r.eras {
        p!("    {},", q(&e.name.text()));
    }
    p!("];");
    p!("");
    p!("/// `DIFF.cost_factor` per difficulty level.");
    p!("pub const DIFFICULTY_COST_FACTOR: [i32; {}] = {:?};", r.difficulties.len(), r.difficulties.iter().map(|d| d.cost_factor).collect::<Vec<_>>());
    p!("/// `WSIZ.tech_rate` per world size.");
    p!("pub const WORLD_TECH_RATE: [i32; {}] = {:?};", r.world_sizes.len(), r.world_sizes.iter().map(|d| d.tech_rate).collect::<Vec<_>>());
    p!("");

    // --- valuation tables ---------------------------------------------------
    p!("const TFRM: [i32; {}] = {:?};", r.worker_jobs.len(), r.worker_jobs.iter().map(|j| j.required_tech).collect::<Vec<_>>());
    p!("const GOOD: [i32; {}] = {:?};", r.goods.len(), r.goods.iter().map(|j| j.prerequisite).collect::<Vec<_>>());
    p!("const GOVT: [i32; {}] = {:?};", r.governments.len(), r.governments.iter().map(|j| j.prerequisite_tech).collect::<Vec<_>>());
    p!("const CTZN: [i32; {}] = {:?};", r.citizens.len(), r.citizens.iter().map(|j| j.prerequisite).collect::<Vec<_>>());
    p!("/// `(required_tech, available_to_civs, ai_strategies, needs_resource)`.");
    p!("const PRTO: [(i32, u32, u32, bool); {}] = [", r.unit_types.len());
    for u in &r.unit_types {
        let res = u.required_resource_1 != -1 || u.required_resource_2 != -1 || u.required_resource_3 != -1;
        p!("    ({}, {:#x}, {:#x}, {}),", u.required_tech, u.available_to_civs as u32, u.ai_strategies, res);
    }
    p!("];");
    p!("/// `(required_advance, spaceship_part, improvement_flags, other_characteristics, flavors)`.");
    p!("const BLDG: [(i32, bool, u32, u32, u32); {}] = [", r.buildings.len());
    for b in &r.buildings {
        p!(
            "    ({}, {}, {:#x}, {:#x}, {:#x}),",
            b.required_advance,
            b.spaceship_part != -1,
            b.improvement_flags as u32,
            b.other_characteristics as u32,
            b.flavors as u32
        );
    }
    p!("];");
    let flav: Vec<Vec<i32>> = biq
        .flavors
        .as_ref()
        .map(|f| f.flavors.iter().map(|x| x.relations.clone()).collect())
        .unwrap_or_default();
    p!("const FLAVORS: [&[i32]; {}] = [", flav.len());
    for row in &flav {
        p!("    &{row:?},");
    }
    p!("];");
    p!("");

    // --- civilizations ------------------------------------------------------
    p!("/// The `RACE` facts the research and diplomacy rules read for one civ.");
    p!("#[derive(Clone, Copy, Debug)]");
    p!("pub struct RaceFacts {{");
    p!("    /// `RACE` row.");
    p!("    pub race: u32,");
    p!("    /// `flavors` mask (mem `+0x960`).");
    p!("    pub flavors: u32,");
    p!("    /// `build_often` mask (mem `+0x954`).");
    p!("    pub build_often: u32,");
    p!("    /// `traits` mask (mem `+0x948`).");
    p!("    pub traits: u32,");
    p!("    /// `aggression` (the AI's attitude base, clamped to -2..=2).");
    p!("    pub aggression: i32,");
    p!("    /// `culture_group` (mem `+0x90C`).");
    p!("    pub culture_group: i32,");
    p!("    /// `shunned_government` (mem `+0x920`), a `GOVT` row or -1.");
    p!("    pub shunned_government: i32,");
    p!("    /// `favorite_government` (mem `+0x924`), a `GOVT` row or -1.");
    p!("    pub favorite_government: i32,");
    p!("    /// `scientific_leader_count`... free advances, `-1` for none.");
    p!("    pub free_techs: [i32; 4],");
    p!("}}");
    p!("");
    p!("/// The playable civilizations, in the game's order.");
    p!("pub const RACES: [RaceFacts; {}] = [", CIVS.len());
    for name in CIVS {
        let Some((i, c)) = r
            .civilizations
            .iter()
            .enumerate()
            .find(|(_, c)| c.civilization_name.text() == name)
        else {
            eprintln!("no RACE called {name}");
            return ExitCode::from(1);
        };
        let ext = c.conquests.as_ref();
        p!(
            "    RaceFacts {{ race: {i}, flavors: {:#x}, build_often: {:#x}, traits: {:#x}, aggression: {}, culture_group: {}, shunned_government: {}, favorite_government: {}, free_techs: {:?} }}, // {name}",
            ext.map_or(0, |e| e.flavors),
            c.build_often,
            c.traits,
            c.aggression,
            c.culture_group,
            c.shunned_government,
            c.favorite_government,
            c.free_techs
        );
    }
    p!("];");
    p!("");

    // --- what unlocks the game's productions -------------------------------
    p!("/// `(production, required advance)` of the units and buildings the game builds.");
    p!("pub const UNLOCKS: [(&str, i32); {}] = [", UNITS.len() + BLDGS.len());
    for n in UNITS {
        let Some(u) = r.unit_types.iter().find(|u| u.name.text() == n) else {
            eprintln!("no PRTO called {n}");
            return ExitCode::from(1);
        };
        p!("    ({}, {}),", q(n), u.required_tech);
    }
    for n in BLDGS {
        let Some(b) = r.buildings.iter().find(|b| b.name.text() == n) else {
            eprintln!("no BLDG called {n}");
            return ExitCode::from(1);
        };
        p!("    ({}, {}),", q(n), b.required_advance);
    }
    p!("];");
    p!("");

    // --- constructors -------------------------------------------------------
    p!("/// The advance rules for `civ3mapgen::research`.");
    p!("pub fn rules() -> Rules {{");
    p!("    Rules {{");
    p!("        techs: TECHS");
    p!("            .iter()");
    p!("            .map(|&(cost, era, prereq, flags, flavors)| TechRow {{ cost, era, prereq, flags, flavors }})");
    p!("            .collect(),");
    p!("        future_tech_cost: FUTURE_TECH_COST,");
    p!("        max_research_turns: MAX_RESEARCH_TIME,");
    p!("        min_research_turns: MIN_RESEARCH_TIME,");
    p!("    }}");
    p!("}}");
    p!("");
    p!("/// The tables the AI valuation walks.");
    p!("pub fn tables() -> Tables {{");
    p!("    Tables {{");
    p!("        tfrm_required: TFRM.to_vec(),");
    p!("        good_prerequisite: GOOD.to_vec(),");
    p!("        units: PRTO");
    p!("            .iter()");
    p!("            .map(|&(required_tech, available_to_civs, ai_strategies, needs_resource)| UnitRow {{");
    p!("                required_tech,");
    p!("                available_to_civs,");
    p!("                ai_strategies,");
    p!("                needs_resource,");
    p!("            }})");
    p!("            .collect(),");
    p!("        govt_prerequisite: GOVT.to_vec(),");
    p!("        bldgs: BLDG");
    p!("            .iter()");
    p!("            .map(|&(required_advance, spaceship_part, improvement_flags, other_characteristics, flavors)| BldgRow {{");
    p!("                required_advance,");
    p!("                spaceship_part,");
    p!("                improvement_flags,");
    p!("                other_characteristics,");
    p!("                flavors,");
    p!("            }})");
    p!("            .collect(),");
    p!("        ctzn_prerequisite: CTZN.to_vec(),");
    p!("        flavors: FLAVORS.iter().map(|r| r.to_vec()).collect(),");
    p!("    }}");
    p!("}}");
    p!("");

    // --- the check ---------------------------------------------------------------
    p!("#[cfg(test)]");
    p!("mod tests {{");
    p!("    use super::*;");
    p!("");
    p!("    #[test]");
    p!("    fn techs_match_the_biq() {{");
    p!("        // TECH rows (file offsets): name +0, cost +0x40, era +0x44,");
    p!("        // prerequisites +0x54, flags +0x64, flavors +0x68. Skipped without");
    p!("        // the (git-ignored) GOG install.");
    p!("        let path = \"civ3/civ3-gog/app/Conquests/conquests.biq\";");
    p!("        let Ok(raw) = std::fs::read(path) else {{");
    p!("            eprintln!(\"skipped: {{path}} is not installed\");");
    p!("            return;");
    p!("        }};");
    p!("        let body = civ3mapgen::dcl::decompress(&raw).expect(\"biq decodes\");");
    p!("        let tech = civ3mapgen::dcl::sections(&body)");
    p!("            .into_iter()");
    p!("            .find(|s| s.tag_str() == \"TECH\")");
    p!("            .expect(\"TECH section\");");
    p!("        assert_eq!(tech.count as usize, TECH_NAMES.len());");
    p!("        let dword = |r: &[u8], at: usize| i32::from_le_bytes(r[at..at + 4].try_into().unwrap());");
    p!("        for (i, &(cost, era, prereq, flags, flavors)) in TECHS.iter().enumerate() {{");
    p!("            let row = tech.row(&body, i as u32).unwrap();");
    p!("            let name = &row[0..32];");
    p!("            let name = &name[..name.iter().position(|&c| c == 0).unwrap_or(name.len())];");
    p!("            assert_eq!(name, TECH_NAMES[i].as_bytes());");
    p!("            assert_eq!((cost, era), (dword(row, 0x40), dword(row, 0x44)), \"{{}}\", TECH_NAMES[i]);");
    p!("            for k in 0..4 {{");
    p!("                assert_eq!(prereq[k], dword(row, 0x54 + 4 * k), \"{{}}\", TECH_NAMES[i]);");
    p!("            }}");
    p!("            assert_eq!((flags, flavors), (dword(row, 0x64) as u32, dword(row, 0x68) as u32 & 0x7F), \"{{}}\", TECH_NAMES[i]);");
    p!("        }}");
    p!("    }}");
    p!("");
    p!("    #[test]");
    p!("    fn the_tables_are_consistent() {{");
    p!("        let r = rules();");
    p!("        let t = r.count();");
    p!("        for (i, row) in r.techs.iter().enumerate() {{");
    p!("            for &p in &row.prereq {{");
    p!("                assert!(p == -1 || (0..t).contains(&p), \"{{}} prerequisite {{p}}\", TECH_NAMES[i]);");
    p!("            }}");
    p!("        }}");
    p!("        let tb = tables();");
    p!("        assert!(tb.units.iter().all(|u| u.required_tech >= -1 && u.required_tech < t));");
    p!("        assert!(tb.bldgs.iter().all(|b| b.required_advance >= -1 && b.required_advance < t));");
    p!("        assert_eq!(tb.flavors.len(), 7);");
    p!("    }}");
    p!("}}");

    print!("{o}");
    ExitCode::SUCCESS
}
