//! Generate `src/rules_data.rs`, the research and diplomacy rules the game
//! hard-codes (the same approach as the combat factors in `src/combat.rs`:
//! the table lives in the source, a corpus-skipping test checks it against
//! the file).
//!
//! ```text
//! cargo run --release --manifest-path biq/Cargo.toml --example gen_game_rules \
//!     -- civ3/civ3-gog/app/Conquests/conquests.biq > src/rules_data.rs
//! ```
use civ3_biq::Biq;
use civ3_biq::sections::bldg::other_characteristics as oc;
use civ3_biq::sections::prto::ability as ab;
use std::fmt::Write as _;
use std::process::ExitCode;

/// The civilizations the game plays, as `RACE.civilization_name` values.
const CIVS: [&str; 4] = ["Japan", "Rome", "Egypt", "China"];
/// The same list, for the unit-availability mask.
const RACES_OF_CIVS: [&str; 4] = CIVS;

/// Improvements whose effects the game implements, by `BLDG` name. Every
/// great wonder is playable besides `BLDG_NOT_PLAYABLE` (they all pay
/// culture and the game's border and score rules use it).
const BLDG_PLAYABLE: &[&str] = &[
    "Barracks",
    "Granary",
    "Temple",
    "Marketplace",
    "Library",
    "Courthouse",
    "Walls",
    "Aqueduct",
    "Bank",
    "Cathedral",
    "University",
    "Colosseum",
    "Factory",
    "Manufacturing Plant",
    "Hydro Plant",
    "Solar Plant",
    "Hospital",
    "Research Lab",
    "Harbor",
    "Stock Exchange",
    "Civil Defense",
    "Wealth",
];
/// Great wonders with effects the game cannot honor yet.
const BLDG_NOT_PLAYABLE: &[&str] = &["The Manhattan Project", "The United Nations"];

fn is_great_wonder(other: u32) -> bool {
    other & oc::WONDER != 0
}

fn q(s: &str) -> String {
    format!("{s:?}")
}

/// `Three-Man Chariot` -> `ThreeManChariot`.
fn ident(name: &str) -> String {
    let mut out = String::new();
    let mut up = true;
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            if up {
                out.extend(c.to_uppercase());
            } else {
                out.push(c);
            }
            up = false;
        } else if c != '\'' {
            up = true;
        }
    }
    out
}

/// The `Art/Units` folder of a unit, when the install has one (Conquests
/// folders win over the base game's).
fn art_dir(name: &str) -> Option<String> {
    let want = match name {
        "Warrior" => "warrior",
        "Chariot" => "chariot",
        "Three-Man Chariot" => "Three Man Chariot",
        "Chasqui Scout" => "Chasquis Scout",
        "Modern Paratrooper" => "Paratrooper",
        "Mech Infantry" => "Mech Infantry",
        "Javelin Thrower" => "Javelin Thrower",
        // The Ancient Age art; the later eras' art would follow the era.
        "Leader" => "Leader Ancient Times",
        "Army" => "Army Ancient Times",
        other => other,
    };
    for root in [
        "civ3/civ3-gog/app/Conquests/Art/Units",
        "civ3/civ3-gog/app/Art/Units",
    ] {
        if std::path::Path::new(root).join(want).is_dir() {
            return Some(want.to_string());
        }
    }
    None
}

fn main() -> ExitCode {
    let Some(path) = std::env::args().nth(1) else {
        eprintln!("usage: gen_game_rules conquests.biq > src/rules_data.rs");
        return ExitCode::from(2);
    };
    let biq = match Biq::read_file(&path) {
        Ok(b) => b,
        Err(e) => {
            eprintln!("{path}: {e}");
            return ExitCode::from(1);
        }
    };
    let r = &biq.rules;
    let mut o = String::new();
    let w = &mut o;
    macro_rules! p {
        ($($a:tt)*) => { writeln!(w, $($a)*).unwrap() };
    }

    p!("//! Research and diplomacy rules of `conquests.biq`, hard-coded.");
    p!("//!");
    p!("//! @generated by `biq/examples/gen_game_rules.rs`; do not edit by hand.");
    p!("//! `tests::techs_match_the_biq` (here) re-reads the file and compares every");
    p!("//! advance when the game install is present; the other tables are checked by");
    p!("//! re-running the generator and diffing.");
    p!("#![allow(clippy::type_complexity)]");
    p!("");
    p!("use crate::cities::Production;");
    p!("use crate::roster::{{BldgDef, UnitRow}};");
    p!("use crate::units::UnitType;");
    p!("use civ3mapgen::research::{{Rules, TechRow}};");
    p!("use civ3mapgen::research_ai::{{BldgRow, Tables, UnitRow as AiUnitRow}};");
    p!("");

    // --- advances -----------------------------------------------------------
    p!("/// Name of every advance, in `TECH` order.");
    p!("pub const TECH_NAMES: [&str; {}] = [", r.techs.len());
    for t in &r.techs {
        p!("    {},", q(&t.name.text()));
    }
    p!("];");
    p!("");
    p!("/// `(cost, era, prerequisites, flags, flavors)` of every advance.");
    p!("const TECHS: [(i32, i32, [i32; 4], u32, u32); {}] = [", r.techs.len());
    for t in &r.techs {
        p!(
            "    ({}, {}, {:?}, {:#x}, {:#x}),",
            t.cost,
            t.era,
            t.prerequisites,
            t.flags,
            t.flavors
        );
    }
    p!("];");
    p!("");
    p!("/// `(era, icon, x, y)` of every advance: the era page of the Science");
    p!("/// Advisor it sits on, its icon's index in the tech icon sheets, and its");
    p!("/// box's top-left on that page (`TECH` +0x44, +0x48, +0x4C, +0x50).");
    p!("pub const TECH_TREE: [(i32, i32, i32, i32); {}] = [", r.techs.len());
    for t in &r.techs {
        p!("    ({}, {}, {}, {}),", t.era, t.icon, t.tree_x, t.tree_y);
    }
    p!("];");
    p!("");
    let g = &r.general_rules[0];
    p!("/// `RULE` future technology cost.");
    p!("pub const FUTURE_TECH_COST: i32 = {};", g.future_tech_cost);
    p!("/// `RULE` maximum research time.");
    p!("pub const MAX_RESEARCH_TIME: i32 = {};", g.max_research_time);
    p!("/// `RULE` minimum research time.");
    p!("pub const MIN_RESEARCH_TIME: i32 = {};", g.min_research_time);
    p!("/// `RULE` upgrade cost: gold per shield of price difference (`unit-upgrades.md` 6).");
    p!("pub const UPGRADE_COST: i32 = {};", g.upgrade_cost);
    p!("");
    p!("/// `ERAS` names.");
    p!("pub const ERA_NAMES: [&str; {}] = [", r.eras.len());
    for e in &r.eras {
        p!("    {},", q(&e.name.text()));
    }
    p!("];");
    p!("");
    p!("/// `DIFF.cost_factor` per difficulty level.");
    p!("pub const DIFFICULTY_COST_FACTOR: [i32; {}] = {:?};", r.difficulties.len(), r.difficulties.iter().map(|d| d.cost_factor).collect::<Vec<_>>());
    p!("/// `WSIZ.tech_rate` per world size.");
    p!("pub const WORLD_TECH_RATE: [i32; {}] = {:?};", r.world_sizes.len(), r.world_sizes.iter().map(|d| d.tech_rate).collect::<Vec<_>>());
    p!("");

    // --- valuation tables ---------------------------------------------------
    p!("const TFRM: [i32; {}] = {:?};", r.worker_jobs.len(), r.worker_jobs.iter().map(|j| j.required_tech).collect::<Vec<_>>());
    p!("/// `GOOD.prerequisite` per `GOOD` row (strategic resources need it to be usable).\npub const GOOD: [i32; {}] = {:?};", r.goods.len(), r.goods.iter().map(|j| j.prerequisite).collect::<Vec<_>>());
    p!("const GOVT: [i32; {}] = {:?};", r.governments.len(), r.governments.iter().map(|j| j.prerequisite_tech).collect::<Vec<_>>());
    p!("const CTZN: [i32; {}] = {:?};", r.citizens.len(), r.citizens.iter().map(|j| j.prerequisite).collect::<Vec<_>>());
    p!("/// `(required_tech, available_to_civs, ai_strategies, needs_resource)`.");
    p!("const PRTO: [(i32, u32, u32, bool); {}] = [", r.unit_types.len());
    for u in &r.unit_types {
        let res = u.required_resource_1 != -1 || u.required_resource_2 != -1 || u.required_resource_3 != -1;
        p!("    ({}, {:#x}, {:#x}, {}),", u.required_tech, u.available_to_civs as u32, u.ai_strategies, res);
    }
    p!("];");
    p!("/// `(required_advance, spaceship_part, improvement_flags, other_characteristics, flavors)`.");
    p!("const BLDG: [(i32, bool, u32, u32, u32); {}] = [", r.buildings.len());
    for b in &r.buildings {
        p!(
            "    ({}, {}, {:#x}, {:#x}, {:#x}),",
            b.required_advance,
            b.spaceship_part != -1,
            b.improvement_flags as u32,
            b.other_characteristics as u32,
            b.flavors as u32
        );
    }
    p!("];");
    let flav: Vec<Vec<i32>> = biq
        .flavors
        .as_ref()
        .map(|f| f.flavors.iter().map(|x| x.relations.clone()).collect())
        .unwrap_or_default();
    p!("const FLAVORS: [&[i32]; {}] = [", flav.len());
    for row in &flav {
        p!("    &{row:?},");
    }
    p!("];");
    p!("");

    // --- civilizations ------------------------------------------------------
    p!("/// The `RACE` facts the research and diplomacy rules read for one civ.");
    p!("#[derive(Clone, Copy, Debug)]");
    p!("pub struct RaceFacts {{");
    p!("    /// `RACE` row.");
    p!("    pub race: u32,");
    p!("    /// `flavors` mask (mem `+0x960`).");
    p!("    pub flavors: u32,");
    p!("    /// `build_often` mask (mem `+0x954`).");
    p!("    pub build_often: u32,");
    p!("    /// `traits` mask (mem `+0x948`).");
    p!("    pub traits: u32,");
    p!("    /// `aggression` (the AI's attitude base, clamped to -2..=2).");
    p!("    pub aggression: i32,");
    p!("    /// `culture_group` (mem `+0x90C`).");
    p!("    pub culture_group: i32,");
    p!("    /// `shunned_government` (mem `+0x920`), a `GOVT` row or -1.");
    p!("    pub shunned_government: i32,");
    p!("    /// `favorite_government` (mem `+0x924`), a `GOVT` row or -1.");
    p!("    pub favorite_government: i32,");
    p!("    /// `scientific_leader_count`... free advances, `-1` for none.");
    p!("    pub free_techs: [i32; 4],");
    p!("}}");
    p!("");
    p!("/// The playable civilizations, in the game's order.");
    p!("pub const RACES: [RaceFacts; {}] = [", CIVS.len());
    for name in CIVS {
        let Some((i, c)) = r
            .civilizations
            .iter()
            .enumerate()
            .find(|(_, c)| c.civilization_name.text() == name)
        else {
            eprintln!("no RACE called {name}");
            return ExitCode::from(1);
        };
        let ext = c.conquests.as_ref();
        p!(
            "    RaceFacts {{ race: {i}, flavors: {:#x}, build_often: {:#x}, traits: {:#x}, aggression: {}, culture_group: {}, shunned_government: {}, favorite_government: {}, free_techs: {:?} }}, // {name}",
            ext.map_or(0, |e| e.flavors),
            c.build_often,
            c.traits,
            c.aggression,
            c.culture_group,
            c.shunned_government,
            c.favorite_government,
            c.free_techs
        );
    }
    p!("];");
    p!("");

    // --- the unit and building rosters -------------------------------------
    let our_mask: u32 = RACES_OF_CIVS
        .iter()
        .map(|n| {
            let i = r
                .civilizations
                .iter()
                .position(|c| c.civilization_name.text() == *n)
                .unwrap_or_else(|| panic!("no RACE called {n}"));
            1u32 << i
        })
        .fold(0, |a, b| a | b);
    let nu = r.unit_types.len();
    let nb = r.buildings.len();
    p!("/// Number of `PRTO` rows: `UnitType(i)` is row `i`, `Production(i)` the same unit.");
    p!("pub const UNIT_COUNT: usize = {nu};");
    p!("/// Number of `BLDG` rows: `Production(UNIT_COUNT + i)` is row `i`.");
    p!("pub const BLDG_COUNT: usize = {nb};");
    p!("");
    p!("/// Every `PRTO` row.");
    p!("pub static UNITS: [UnitRow; {nu}] = [");
    let mut unit_names = vec![];
    for (i, u) in r.unit_types.iter().enumerate() {
        let name = u.name.text();
        let art = art_dir(&name);
        let abil = u.abilities;
        let excluded = abil
            & (ab::KING
                | ab::FLAG_UNIT
                | ab::CRUISE_MISSILE
                | ab::NUCLEAR_WEAPON
                | ab::TACTICAL_MISSILE)
            != 0;
        let playable = u.alt_strategy_of == -1
            && (u.unit_class == 0 || &*name == "Galley")
            && !excluded
            && ((u.available_to_civs as u32) & our_mask != 0 || &*name == "Scout")
            && art.is_some();
        let sight = match (u.unit_class, &*name) {
            (1, _) => 2,
            (2, _) => 3,
            (_, "Scout" | "Explorer" | "Chasqui Scout") => 2,
            _ => 1,
        };
        p!(
            "    UnitRow {{ name: {}, art: {}, icon: {}, attack: {}, defense: {}, moves: {}, sight: {sight}, hp_bonus: {}, cost: {}, pop_cost: {}, tech: {}, upgrade_to: {}, resources: [{}, {}, {}], abilities: {:#x}, special: {:#x}, worker: {:#x}, bombard: {}, bomb_range: {}, rof: {}, capacity: {}, class: {}, races: {:#x}, ai: {:#x}, zoc: {}, playable: {playable} }}, // {i}",
            q(&name),
            q(if playable { art.as_deref().unwrap_or("") } else { "" }),
            u.icon,
            u.attack,
            u.defense,
            u.movement,
            u.hit_point_bonus,
            u.shield_cost,
            u.population_cost,
            u.required_tech,
            u.upgrade_to,
            u.required_resource_1,
            u.required_resource_2,
            u.required_resource_3,
            abil,
            u.special_actions,
            u.worker_actions,
            u.bombard_strength,
            u.bombard_range,
            u.rate_of_fire,
            u.transport_capacity,
            u.unit_class,
            u.available_to_civs as u32,
            u.ai_strategies,
            u.zone_of_control != 0,
        );
        unit_names.push((i, name, u.alt_strategy_of));
    }
    p!("];");
    p!("");
    p!("/// Every `BLDG` row.");
    p!("pub static BLDGS: [BldgDef; {nb}] = [");
    let mut bldg_names = vec![];
    for (i, b) in r.buildings.iter().enumerate() {
        let name = b.name.text();
        let playable = BLDG_PLAYABLE.iter().any(|n| *n == &*name) || is_great_wonder(b.other_characteristics as u32) && !BLDG_NOT_PLAYABLE.iter().any(|n| *n == &*name);
        p!(
            "    BldgDef {{ name: {}, cost: {}, upkeep: {}, culture: {}, tech: {}, obsolete: {}, requires: {}, govt: {}, resources: [{}, {}], happy: {}, happy_all: {}, unhappy: {}, unhappy_all: {}, defense: {}, production: {}, grant_all: {}, grant_continent: {}, doubles: {}, flags: {:#x}, other: {:#x}, small: {:#x}, wonder: {:#x}, playable: {playable} }}, // {i}",
            q(&name),
            b.cost,
            b.maintenance,
            b.culture,
            b.required_advance,
            b.rendered_obsolete_by,
            b.required_improvement,
            b.required_government,
            b.required_resource_1,
            b.required_resource_2,
            b.happy_faces,
            b.happy_faces_all_cities,
            b.unhappy_faces,
            b.unhappy_faces_all_cities,
            b.defense_bonus,
            b.production,
            b.gain_in_every_city,
            b.gain_in_every_city_on_continent,
            b.doubles_happiness_of,
            b.improvement_flags as u32,
            b.other_characteristics as u32,
            b.small_wonder_flags as u32,
            b.wonder_flags as u32,
        );
        bldg_names.push((i, name));
    }
    p!("];");
    p!("");
    p!("#[allow(non_upper_case_globals)]");
    p!("impl UnitType {{");
    let mut seen = std::collections::HashSet::new();
    for (i, name, alt) in &unit_names {
        let id = ident(name);
        if *alt != -1 || !seen.insert(id.clone()) {
            continue;
        }
        p!("    pub const {id}: UnitType = UnitType({i});");
    }
    p!("}}");
    p!("");
    p!("#[allow(non_upper_case_globals)]");
    p!("impl Production {{");
    let mut seen_p = std::collections::HashSet::new();
    for (i, name, alt) in &unit_names {
        let id = ident(name);
        if *alt != -1 || !seen_p.insert(id.clone()) {
            continue;
        }
        p!("    pub const {id}: Production = Production({i});");
    }
    for (i, name) in &bldg_names {
        let id = ident(name);
        if !seen_p.insert(id.clone()) {
            continue;
        }
        p!("    pub const {id}: Production = Production({});", nu + i);
    }
    p!("}}");
    p!("");

    // --- constructors -------------------------------------------------------
    p!("/// The advance rules for `civ3mapgen::research`.");
    p!("pub fn rules() -> Rules {{");
    p!("    Rules {{");
    p!("        techs: TECHS");
    p!("            .iter()");
    p!("            .map(|&(cost, era, prereq, flags, flavors)| TechRow {{ cost, era, prereq, flags, flavors }})");
    p!("            .collect(),");
    p!("        future_tech_cost: FUTURE_TECH_COST,");
    p!("        max_research_turns: MAX_RESEARCH_TIME,");
    p!("        min_research_turns: MIN_RESEARCH_TIME,");
    p!("    }}");
    p!("}}");
    p!("");
    p!("/// The tables the AI valuation walks.");
    p!("pub fn tables() -> Tables {{");
    p!("    Tables {{");
    p!("        tfrm_required: TFRM.to_vec(),");
    p!("        good_prerequisite: GOOD.to_vec(),");
    p!("        units: PRTO");
    p!("            .iter()");
    p!("            .map(|&(required_tech, available_to_civs, ai_strategies, needs_resource)| AiUnitRow {{");
    p!("                required_tech,");
    p!("                available_to_civs,");
    p!("                ai_strategies,");
    p!("                needs_resource,");
    p!("            }})");
    p!("            .collect(),");
    p!("        govt_prerequisite: GOVT.to_vec(),");
    p!("        bldgs: BLDG");
    p!("            .iter()");
    p!("            .map(|&(required_advance, spaceship_part, improvement_flags, other_characteristics, flavors)| BldgRow {{");
    p!("                required_advance,");
    p!("                spaceship_part,");
    p!("                improvement_flags,");
    p!("                other_characteristics,");
    p!("                flavors,");
    p!("            }})");
    p!("            .collect(),");
    p!("        ctzn_prerequisite: CTZN.to_vec(),");
    p!("        flavors: FLAVORS.iter().map(|r| r.to_vec()).collect(),");
    p!("    }}");
    p!("}}");
    p!("");

    // --- the check ---------------------------------------------------------------
    p!("#[cfg(test)]");
    p!("mod tests {{");
    p!("    use super::*;");
    p!("");
    p!("    #[test]");
    p!("    fn techs_match_the_biq() {{");
    p!("        // TECH rows (file offsets): name +0, cost +0x40, era +0x44,");
    p!("        // prerequisites +0x54, flags +0x64, flavors +0x68. Skipped without");
    p!("        // the (git-ignored) GOG install.");
    p!("        let path = \"civ3/civ3-gog/app/Conquests/conquests.biq\";");
    p!("        let Ok(raw) = std::fs::read(path) else {{");
    p!("            eprintln!(\"skipped: {{path}} is not installed\");");
    p!("            return;");
    p!("        }};");
    p!("        let body = civ3mapgen::dcl::decompress(&raw).expect(\"biq decodes\");");
    p!("        let tech = civ3mapgen::dcl::sections(&body)");
    p!("            .into_iter()");
    p!("            .find(|s| s.tag_str() == \"TECH\")");
    p!("            .expect(\"TECH section\");");
    p!("        assert_eq!(tech.count as usize, TECH_NAMES.len());");
    p!("        let dword = |r: &[u8], at: usize| i32::from_le_bytes(r[at..at + 4].try_into().unwrap());");
    p!("        for (i, &(cost, era, prereq, flags, flavors)) in TECHS.iter().enumerate() {{");
    p!("            let row = tech.row(&body, i as u32).unwrap();");
    p!("            let name = &row[0..32];");
    p!("            let name = &name[..name.iter().position(|&c| c == 0).unwrap_or(name.len())];");
    p!("            assert_eq!(name, TECH_NAMES[i].as_bytes());");
    p!("            assert_eq!((cost, era), (dword(row, 0x40), dword(row, 0x44)), \"{{}}\", TECH_NAMES[i]);");
    p!("            for k in 0..4 {{");
    p!("                assert_eq!(prereq[k], dword(row, 0x54 + 4 * k), \"{{}}\", TECH_NAMES[i]);");
    p!("            }}");
    p!("            assert_eq!((flags, flavors), (dword(row, 0x64) as u32, dword(row, 0x68) as u32 & 0x7F), \"{{}}\", TECH_NAMES[i]);");
    p!("        }}");
    p!("    }}");
    p!("");
    p!("    #[test]");
    p!("    fn the_tables_are_consistent() {{");
    p!("        let r = rules();");
    p!("        let t = r.count();");
    p!("        for (i, row) in r.techs.iter().enumerate() {{");
    p!("            for &p in &row.prereq {{");
    p!("                assert!(p == -1 || (0..t).contains(&p), \"{{}} prerequisite {{p}}\", TECH_NAMES[i]);");
    p!("            }}");
    p!("        }}");
    p!("        let tb = tables();");
    p!("        assert!(tb.units.iter().all(|u| u.required_tech >= -1 && u.required_tech < t));");
    p!("        assert!(tb.bldgs.iter().all(|b| b.required_advance >= -1 && b.required_advance < t));");
    p!("        assert_eq!(tb.flavors.len(), 7);");
    p!("    }}");
    p!("}}");

    print!("{o}");
    ExitCode::SUCCESS
}
