//! Research and diplomacy rules of `conquests.biq`, hard-coded.
//!
//! @generated by `biq/examples/gen_game_rules.rs`; do not edit by hand.
//! `tests::techs_match_the_biq` (here) re-reads the file and compares every
//! advance when the game install is present; the other tables are checked by
//! re-running the generator and diffing.
#![allow(clippy::type_complexity)]

use civ3mapgen::research::{Rules, TechRow};
use civ3mapgen::research_ai::{BldgRow, Tables, UnitRow};

/// Name of every advance, in `TECH` order.
pub const TECH_NAMES: [&str; 83] = [
    "Bronze Working",
    "Masonry",
    "Alphabet",
    "Pottery",
    "The Wheel",
    "Warrior Code",
    "Ceremonial Burial",
    "Iron Working",
    "Writing",
    "Mysticism",
    "Mathematics",
    "Philosophy",
    "Code of Laws",
    "Literature",
    "Map Making",
    "Horseback Riding",
    "Polytheism",
    "Currency",
    "The Republic",
    "Monarchy",
    "Construction",
    "Monotheism",
    "Feudalism",
    "Engineering",
    "Theology",
    "Chivalry",
    "Invention",
    "Printing Press",
    "Music Theory",
    "Education",
    "Gunpowder",
    "Banking",
    "Astronomy",
    "Chemistry",
    "Democracy",
    "Economics",
    "Navigation",
    "Physics",
    "Metallurgy",
    "Free Artistry",
    "Theory of Gravity",
    "Magnetism",
    "Military Tradition",
    "Nationalism",
    "Steam Power",
    "Medicine",
    "Communism",
    "Industrialization",
    "Electricity",
    "Scientific Method",
    "Sanitation",
    "Espionage",
    "The Corporation",
    "Refining",
    "Steel",
    "Atomic Theory",
    "Combustion",
    "Replaceable Parts",
    "Flight",
    "Amphibious War",
    "Mass Production",
    "Electronics",
    "Motorized Transportation",
    "Advanced Flight",
    "Rocketry",
    "Fission",
    "Computers",
    "Recycling",
    "Space Flight",
    "Nuclear Power",
    "Superconductor",
    "Miniaturization",
    "Ecology",
    "Synthetic Fibers",
    "Satellites",
    "The Laser",
    "Genetics",
    "Stealth",
    "Smart Weapons",
    "Robotics",
    "Integrated Defense",
    "Ironclads",
    "Fascism",
];

/// `(cost, era, prerequisites, flags, flavors)` of every advance.
const TECHS: [(i32, i32, [i32; 4], u32, u32); 83] = [
    (3, 0, [-1, -1, -1, -1], 0x0, 0x0),
    (4, 0, [-1, -1, -1, -1], 0x0, 0x0),
    (5, 0, [-1, -1, -1, -1], 0x0, 0x0),
    (2, 0, [-1, -1, -1, -1], 0x0, 0x0),
    (4, 0, [-1, -1, -1, -1], 0x0, 0x0),
    (3, 0, [-1, -1, -1, -1], 0x0, 0x0),
    (2, 0, [-1, -1, -1, -1], 0x0, 0x0),
    (6, 0, [0, -1, -1, -1], 0x0, 0x0),
    (8, 0, [2, -1, -1, -1], 0x401, 0x0),
    (4, 0, [6, -1, -1, -1], 0x0, 0x0),
    (8, 0, [1, 2, -1, -1], 0x0, 0x0),
    (6, 0, [8, -1, -1, -1], 0x200000, 0x0),
    (10, 0, [8, -1, -1, -1], 0x0, 0x0),
    (10, 0, [8, -1, -1, -1], 0x20000, 0x0),
    (12, 0, [8, 3, -1, -1], 0x200, 0x0),
    (5, 0, [4, 5, -1, -1], 0x0, 0x0),
    (12, 0, [9, -1, -1, -1], 0x0, 0x0),
    (16, 0, [10, -1, -1, -1], 0x0, 0x0),
    (28, 0, [11, 12, -1, -1], 0x20000, 0x0),
    (24, 0, [5, 16, -1, -1], 0x20000, 0x0),
    (20, 0, [7, 10, -1, -1], 0x0, 0x0),
    (36, 1, [-1, -1, -1, -1], 0x0, 0x0),
    (32, 1, [-1, -1, -1, -1], 0x0, 0x0),
    (36, 1, [-1, -1, -1, -1], 0x4, 0x0),
    (40, 1, [21, -1, -1, -1], 0x0, 0x0),
    (32, 1, [21, 22, -1, -1], 0x20000, 0x0),
    (44, 1, [22, 23, -1, -1], 0x0, 0x0),
    (36, 1, [24, -1, -1, -1], 0x30000, 0x0),
    (40, 1, [29, -1, -1, -1], 0x20000, 0x0),
    (44, 1, [24, -1, -1, -1], 0x0, 0x0),
    (48, 1, [26, -1, -1, -1], 0x0, 0x0),
    (52, 1, [29, -1, -1, -1], 0x0, 0x0),
    (56, 1, [29, -1, -1, -1], 0x2000, 0x0),
    (60, 1, [30, -1, -1, -1], 0x0, 0x0),
    (68, 1, [27, 31, -1, -1], 0x20000, 0x0),
    (56, 1, [31, -1, -1, -1], 0x21000, 0x0),
    (56, 1, [32, -1, -1, -1], 0x2c000, 0x0),
    (64, 1, [32, 33, -1, -1], 0x0, 0x0),
    (64, 1, [33, -1, -1, -1], 0x0, 0x0),
    (52, 1, [34, -1, -1, -1], 0x20000, 0x0),
    (68, 1, [37, -1, -1, -1], 0x0, 0x0),
    (68, 1, [37, -1, -1, -1], 0x4000, 0x0),
    (64, 1, [38, -1, -1, -1], 0x20000, 0x0),
    (120, 2, [-1, -1, -1, -1], 0x20930, 0x0),
    (120, 2, [-1, -1, -1, -1], 0x0, 0x0),
    (100, 2, [-1, -1, -1, -1], 0x0, 0x0),
    (120, 2, [43, -1, -1, -1], 0x20000, 0x0),
    (120, 2, [44, -1, -1, -1], 0x0, 0x0),
    (140, 2, [44, -1, -1, -1], 0x2, 0x0),
    (100, 2, [45, 48, -1, -1], 0x0, 0x0),
    (90, 2, [45, -1, -1, -1], 0x20008, 0x0),
    (90, 2, [43, 47, -1, -1], 0x20000, 0x0),
    (100, 2, [47, -1, -1, -1], 0x0, 0x0),
    (160, 2, [52, -1, -1, -1], 0x0, 0x0),
    (140, 2, [52, -1, -1, -1], 0x0, 0x0),
    (200, 2, [49, -1, -1, -1], 0x0, 0x0),
    (160, 2, [53, 54, -1, -1], 0x0, 0x0),
    (140, 2, [48, -1, -1, -1], 0x40000, 0x0),
    (180, 2, [56, -1, -1, -1], 0x0, 0x0),
    (120, 2, [60, -1, -1, -1], 0x20000, 0x0),
    (140, 2, [56, 57, -1, -1], 0x0, 0x0),
    (180, 2, [55, -1, -1, -1], 0x0, 0x0),
    (140, 2, [60, -1, -1, -1], 0x0, 0x0),
    (180, 2, [58, 61, 62, -1], 0x20000, 0x0),
    (240, 3, [-1, -1, -1, -1], 0x0, 0x0),
    (280, 3, [-1, -1, -1, -1], 0x0, 0x0),
    (260, 3, [-1, -1, -1, -1], 0x0, 0x0),
    (240, 3, [72, -1, -1, -1], 0x40, 0x0),
    (300, 3, [64, -1, -1, -1], 0x0, 0x0),
    (280, 3, [65, -1, -1, -1], 0x0, 0x0),
    (300, 3, [65, 68, -1, -1], 0x0, 0x0),
    (320, 3, [66, -1, -1, -1], 0x0, 0x0),
    (260, 3, [-1, -1, -1, -1], 0x0, 0x0),
    (280, 3, [72, -1, -1, -1], 0x0, 0x0),
    (260, 3, [68, -1, -1, -1], 0x400000, 0x0),
    (280, 3, [69, 66, -1, -1], 0x0, 0x0),
    (320, 3, [71, -1, -1, -1], 0x0, 0x0),
    (300, 3, [73, -1, -1, -1], 0x0, 0x0),
    (280, 3, [74, 75, -1, -1], 0x80, 0x0),
    (320, 3, [75, 71, -1, -1], 0x0, 0x0),
    (360, 3, [70, 74, 78, -1], 0x0, 0x0),
    (100, 2, [44, -1, -1, -1], 0x20000, 0x0),
    (130, 2, [43, -1, -1, -1], 0x20000, 0x0),
];

/// `RULE` future technology cost.
pub const FUTURE_TECH_COST: i32 = 400;
/// `RULE` maximum research time.
pub const MAX_RESEARCH_TIME: i32 = 50;
/// `RULE` minimum research time.
pub const MIN_RESEARCH_TIME: i32 = 4;

/// `ERAS` names.
pub const ERA_NAMES: [&str; 4] = [
    "Ancient Times",
    "Middle Ages",
    "Industrial Ages",
    "Modern Times",
];

/// `DIFF.cost_factor` per difficulty level.
pub const DIFFICULTY_COST_FACTOR: [i32; 8] = [20, 12, 10, 9, 8, 7, 6, 4];
/// `WSIZ.tech_rate` per world size.
pub const WORLD_TECH_RATE: [i32; 5] = [160, 200, 240, 320, 400];

const TFRM: [i32; 13] = [-1, -1, 20, -1, 44, 23, -1, -1, -1, 58, 63, 1, 20];
const GOOD: [i32; 26] = [4, 7, 30, 44, 53, 57, 64, 65, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1];
const GOVT: [i32; 8] = [-1, -1, 19, 46, 18, 34, 82, 22];
const CTZN: [i32; 6] = [-1, -1, -1, -1, 43, 57];
/// `(required_tech, available_to_civs, ai_strategies, needs_resource)`.
const PRTO: [(i32, u32, u32, bool); 141] = [
    (-1, 0xfffffffe, 0x2000, false),
    (-1, 0xfffffffe, 0x1000, false),
    (-1, 0x14424140, 0x8, false),
    (32, 0xfffbfffe, 0x8, false),
    (59, 0xfffffffe, 0x1, true),
    (73, 0xfffffffe, 0x1, true),
    (-1, 0xfdffffff, 0x1, false),
    (5, 0x7fffffee, 0x1, false),
    (0, 0xfd7fbff6, 0x2, false),
    (7, 0xffdfeffc, 0x1, true),
    (4, 0xfbfffffa, 0x1, true),
    (15, 0xffff7fff, 0x1, true),
    (22, 0xf77ffff6, 0x2, true),
    (26, 0xfff7fffe, 0x1, false),
    (30, 0xfffffbfe, 0x2, true),
    (25, 0xffbdf57e, 0x1, true),
    (43, 0xfffffffe, 0x1, false),
    (42, 0xffefffbe, 0x1, true),
    (57, 0xfffffffe, 0x1, true),
    (62, 0xffffffde, 0x1, true),
    (66, 0xfffffffe, 0x1, true),
    (73, 0xfffffffe, 0x1, true),
    (10, 0xfffffffe, 0x4, false),
    (38, 0xfffffffe, 0x4, true),
    (57, 0xfffffffe, 0x4, false),
    (79, 0xfffffffe, 0x4, true),
    (64, 0xfffffffe, 0x20, true),
    (68, 0xfffffffe, 0x8000, true),
    (74, 0xfffffffe, 0x10000, true),
    (14, 0xdffffffe, 0x400, false),
    (32, 0xeffffffe, 0x400, false),
    (41, 0xfffefffe, 0x100, true),
    (41, 0xfffffffe, 0x400, false),
    (81, 0xfffffffe, 0x100, true),
    (56, 0xfffffffe, 0x400, true),
    (60, 0xfffffffe, 0x800, true),
    (60, 0xfffffffe, 0x100, true),
    (56, 0xfffffffe, 0x100, true),
    (60, 0xfffffffe, 0x100, true),
    (79, 0xfffffffe, 0x100, true),
    (65, 0xfffffffe, 0x100, true),
    (58, 0xfffffffe, 0x80, true),
    (58, 0xfffffffe, 0x40, true),
    (63, 0xfffffffe, 0x200, true),
    (64, 0xfffffefe, 0x80, true),
    (77, 0xfffffffe, 0x40, true),
    (77, 0xfffffffe, 0x40, true),
    (-1, 0xfffffffe, 0x4000, false),
    (-1, 0xfffffffe, 0x10, false),
    (5, 0x2000, 0x1, false),
    (5, 0x10, 0x1, false),
    (0, 0x8, 0x2, false),
    (0, 0x4000, 0x1, false),
    (7, 0x2, 0x1, true),
    (7, 0x1000, 0x1, true),
    (4, 0x4, 0x1, true),
    (25, 0x80, 0x1, true),
    (15, 0x8000, 0x1, true),
    (30, 0x400, 0x1, true),
    (25, 0x200, 0x1, true),
    (25, 0x800, 0x1, false),
    (42, 0x40, 0x1, true),
    (62, 0x20, 0x1, true),
    (41, 0x10000, 0x100, true),
    (64, 0x100, 0x40, true),
    (41, 0xfffffffe, 0x100, true),
    (25, 0x20000, 0x1, true),
    (32, 0x40000, 0x1, true),
    (26, 0x80000, 0x1, false),
    (42, 0x100000, 0x1, true),
    (7, 0x200000, 0x1, true),
    (25, 0x400000, 0x1, true),
    (0, 0x800000, 0x1, false),
    (38, 0x1000000, 0x4, true),
    (22, 0xffffeffe, 0x1, true),
    (57, 0xfffffffe, 0x1, false),
    (-1, 0x0, 0x40000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x2000000, 0x2, false),
    (4, 0x4000000, 0x1, true),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (32, 0x10000000, 0x100, false),
    (22, 0x8000000, 0x2, true),
    (-1, 0x0, 0x80000, false),
    (23, 0xfffffffe, 0x4, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x0, 0x80000, false),
    (-1, 0x40000000, 0x1, false),
    (5, 0x80000000, 0x1, false),
    (14, 0x20000000, 0x100, false),
    (56, 0xfffffffe, 0x100, true),
    (-1, 0x0, 0x1, false),
    (-1, 0x0, 0x1, false),
    (2, 0xfffffffe, 0x100, false),
    (63, 0xfffffffe, 0x1, true),
    (64, 0xfffffffe, 0x1, false),
    (58, 0xfffffffe, 0x2, false),
    (64, 0xfffffffe, 0x2, false),
    (43, 0xfffffffe, 0x2, false),
    (57, 0xfffffffe, 0x2, true),
    (66, 0xfffffffe, 0x2, true),
    (65, 0xfffffffe, 0x20000, true),
    (0, 0x4000, 0x2, false),
    (7, 0x2, 0x2, true),
    (30, 0x400, 0x2, true),
    (25, 0x200, 0x2, true),
    (64, 0x100, 0x80, true),
    (32, 0x40000, 0x8, true),
    (0, 0x800000, 0x2, false),
    (57, 0xfffffffe, 0x2, false),
    (32, 0x10000000, 0x400, false),
    (-1, 0x40000000, 0x8, false),
    (5, 0x80000000, 0x2, false),
    (14, 0x20000000, 0x400, false),
    (64, 0xfffffffe, 0x2, false),
];
/// `(required_advance, spaceship_part, improvement_flags, other_characteristics, flavors)`.
const BLDG: [(i32, bool, u32, u32, u32); 83] = [
    (1, false, 0x1, 0x0, 0x0),
    (-1, false, 0x2, 0x2, 0x0),
    (3, false, 0x200, 0x0, 0x0),
    (6, false, 0x0, 0x100, 0x0),
    (17, false, 0x410, 0x40, 0x0),
    (13, false, 0x4, 0x20, 0x0),
    (12, false, 0x180, 0x0, 0x0),
    (1, false, 0x0, 0x2, 0x0),
    (20, false, 0x800, 0x400, 0x0),
    (31, false, 0x10, 0x40, 0x0),
    (21, false, 0x0, 0x100, 0x0),
    (29, false, 0x4, 0x20, 0x0),
    (20, false, 0x0, 0x0, 0x0),
    (47, false, 0x0, 0x0, 0x0),
    (79, false, 0x0, 0x0, 0x0),
    (67, false, 0x40, 0x400, 0x0),
    (47, false, 0x2000, 0x0, 0x0),
    (61, false, 0xa000, 0x0, 0x0),
    (69, false, 0x16000, 0x0, 0x0),
    (50, false, 0x1000, 0x0, 0x0),
    (66, false, 0x4, 0x20, 0x0),
    (72, false, 0x20, 0x0, 0x0),
    (64, false, 0x0, 0x2, 0x0),
    (38, false, 0x0, 0x803, 0x0),
    (72, false, 0x2000, 0x400, 0x0),
    (14, false, 0x1120000, 0x843, 0x0),
    (71, false, 0x800000, 0x801, 0x0),
    (58, false, 0x240000, 0x42, 0x0),
    (46, false, 0x400100, 0x0, 0x0),
    (-1, false, 0x80000, 0x0, 0x0),
    (1, false, 0x0, 0x704, 0x0),
    (19, false, 0x0, 0x604, 0x0),
    (0, false, 0x0, 0x8c5, 0x0),
    (14, false, 0x0, 0x8c5, 0x0),
    (13, false, 0x0, 0x24, 0x0),
    (9, false, 0x0, 0x104, 0x0),
    (20, false, 0x0, 0x206, 0x0),
    (22, false, 0x0, 0x6, 0x0),
    (24, false, 0x0, 0x104, 0x0),
    (36, false, 0x0, 0x8c5, 0x0),
    (32, false, 0x0, 0x84, 0x0),
    (39, false, 0x1000, 0x4, 0x0),
    (26, false, 0x0, 0x6, 0x0),
    (28, false, 0x0, 0x114, 0x0),
    (40, false, 0x0, 0x24, 0x0),
    (35, false, 0x0, 0x844, 0x0),
    (47, false, 0x0, 0x404, 0x0),
    (61, false, 0x8000, 0x604, 0x0),
    (49, false, 0x0, 0x24, 0x0),
    (65, false, 0x0, 0x44, 0x0),
    (65, false, 0x0, 0x206, 0x0),
    (76, false, 0x0, 0x424, 0x0),
    (76, false, 0x0, 0x24, 0x0),
    (66, false, 0x0, 0x84, 0x0),
    (-1, false, 0x0, 0x908, 0x0),
    (-1, false, 0x80000000, 0x8, 0x0),
    (-1, false, 0x0, 0x108, 0x0),
    (42, false, 0x0, 0xa, 0x0),
    (-1, false, 0x0, 0xa, 0x0),
    (-1, false, 0x0, 0x8, 0x0),
    (68, false, 0x0, 0x28, 0x0),
    (80, false, 0x0, 0xa, 0x0),
    (51, false, 0x0, 0x2a, 0x0),
    (-1, false, 0x0, 0xa, 0x0),
    (74, true, 0x0, 0x0, 0x0),
    (68, true, 0x0, 0x0, 0x0),
    (68, true, 0x0, 0x0, 0x0),
    (68, true, 0x0, 0x0, 0x0),
    (70, true, 0x0, 0x0, 0x0),
    (70, true, 0x0, 0x0, 0x0),
    (79, true, 0x0, 0x0, 0x0),
    (73, true, 0x0, 0x0, 0x0),
    (75, true, 0x0, 0x0, 0x0),
    (73, true, 0x0, 0x0, 0x0),
    (71, false, 0x0, 0xfe6, 0x0),
    (61, false, 0x0, 0x2, 0x0),
    (52, false, 0x10, 0x40, 0x0),
    (60, false, 0x2000000, 0x840, 0x0),
    (16, false, 0x0, 0x104, 0x0),
    (10, false, 0x40000000, 0x106, 0x0),
    (11, false, 0x0, 0x824, 0x0),
    (25, false, 0x40000000, 0x106, 0x0),
    (51, false, 0x0, 0x8, 0x0),
];
const FLAVORS: [&[i32]; 7] = [
    &[100, 50, 50, 50, 50, 50, 50],
    &[50, 100, 50, 50, 50, 50, 50],
    &[50, 50, 100, 50, 50, 50, 50],
    &[50, 50, 50, 100, 50, 50, 50],
    &[50, 50, 50, 50, 100, 50, 50],
    &[50, 50, 50, 50, 50, 100, 50],
    &[50, 50, 50, 50, 50, 50, 100],
];

/// The `RACE` facts the research and diplomacy rules read for one civ.
#[derive(Clone, Copy, Debug)]
pub struct RaceFacts {
    /// `RACE` row.
    pub race: u32,
    /// `flavors` mask (mem `+0x960`).
    pub flavors: u32,
    /// `build_often` mask (mem `+0x954`).
    pub build_often: u32,
    /// `traits` mask (mem `+0x948`).
    pub traits: u32,
    /// `aggression` (the AI's attitude base, clamped to -2..=2).
    pub aggression: i32,
    /// `culture_group` (mem `+0x90C`).
    pub culture_group: i32,
    /// `shunned_government` (mem `+0x920`), a `GOVT` row or -1.
    pub shunned_government: i32,
    /// `favorite_government` (mem `+0x924`), a `GOVT` row or -1.
    pub favorite_government: i32,
    /// `scientific_leader_count`... free advances, `-1` for none.
    pub free_techs: [i32; 4],
}

/// The playable civilizations, in the game's order.
pub const RACES: [RaceFacts; 4] = [
    RaceFacts { race: 9, flavors: 0x0, build_often: 0x221, traits: 0x11, aggression: 1, culture_group: 4, shunned_government: 4, favorite_government: 7, free_techs: [4, 6, -1, -1] }, // Japan
    RaceFacts { race: 1, flavors: 0x0, build_often: 0x183, traits: 0x3, aggression: 1, culture_group: 2, shunned_government: 3, favorite_government: 4, free_techs: [5, 2, -1, -1] }, // Rome
    RaceFacts { race: 2, flavors: 0x0, build_often: 0x4180, traits: 0x30, aggression: 0, culture_group: 2, shunned_government: 4, favorite_government: 1, free_techs: [6, 1, -1, -1] }, // Egypt
    RaceFacts { race: 7, flavors: 0x0, build_often: 0x580, traits: 0x21, aggression: -1, culture_group: 4, shunned_government: 7, favorite_government: 3, free_techs: [5, 1, -1, -1] }, // China
];

/// `(production, required advance)` of the units and buildings the game builds.
pub const UNLOCKS: [(&str, i32); 10] = [
    ("Warrior", -1),
    ("Archer", 5),
    ("Spearman", 0),
    ("Horseman", 15),
    ("Scout", -1),
    ("Settler", -1),
    ("Worker", -1),
    ("Barracks", -1),
    ("Granary", 3),
    ("Temple", 6),
];

/// The advance rules for `civ3mapgen::research`.
pub fn rules() -> Rules {
    Rules {
        techs: TECHS
            .iter()
            .map(|&(cost, era, prereq, flags, flavors)| TechRow { cost, era, prereq, flags, flavors })
            .collect(),
        future_tech_cost: FUTURE_TECH_COST,
        max_research_turns: MAX_RESEARCH_TIME,
        min_research_turns: MIN_RESEARCH_TIME,
    }
}

/// The tables the AI valuation walks.
pub fn tables() -> Tables {
    Tables {
        tfrm_required: TFRM.to_vec(),
        good_prerequisite: GOOD.to_vec(),
        units: PRTO
            .iter()
            .map(|&(required_tech, available_to_civs, ai_strategies, needs_resource)| UnitRow {
                required_tech,
                available_to_civs,
                ai_strategies,
                needs_resource,
            })
            .collect(),
        govt_prerequisite: GOVT.to_vec(),
        bldgs: BLDG
            .iter()
            .map(|&(required_advance, spaceship_part, improvement_flags, other_characteristics, flavors)| BldgRow {
                required_advance,
                spaceship_part,
                improvement_flags,
                other_characteristics,
                flavors,
            })
            .collect(),
        ctzn_prerequisite: CTZN.to_vec(),
        flavors: FLAVORS.iter().map(|r| r.to_vec()).collect(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn techs_match_the_biq() {
        // TECH rows (file offsets): name +0, cost +0x40, era +0x44,
        // prerequisites +0x54, flags +0x64, flavors +0x68. Skipped without
        // the (git-ignored) GOG install.
        let path = "civ3/civ3-gog/app/Conquests/conquests.biq";
        let Ok(raw) = std::fs::read(path) else {
            eprintln!("skipped: {path} is not installed");
            return;
        };
        let body = civ3mapgen::dcl::decompress(&raw).expect("biq decodes");
        let tech = civ3mapgen::dcl::sections(&body)
            .into_iter()
            .find(|s| s.tag_str() == "TECH")
            .expect("TECH section");
        assert_eq!(tech.count as usize, TECH_NAMES.len());
        let dword = |r: &[u8], at: usize| i32::from_le_bytes(r[at..at + 4].try_into().unwrap());
        for (i, &(cost, era, prereq, flags, flavors)) in TECHS.iter().enumerate() {
            let row = tech.row(&body, i as u32).unwrap();
            let name = &row[0..32];
            let name = &name[..name.iter().position(|&c| c == 0).unwrap_or(name.len())];
            assert_eq!(name, TECH_NAMES[i].as_bytes());
            assert_eq!((cost, era), (dword(row, 0x40), dword(row, 0x44)), "{}", TECH_NAMES[i]);
            for k in 0..4 {
                assert_eq!(prereq[k], dword(row, 0x54 + 4 * k), "{}", TECH_NAMES[i]);
            }
            assert_eq!((flags, flavors), (dword(row, 0x64) as u32, dword(row, 0x68) as u32 & 0x7F), "{}", TECH_NAMES[i]);
        }
    }

    #[test]
    fn the_tables_are_consistent() {
        let r = rules();
        let t = r.count();
        for (i, row) in r.techs.iter().enumerate() {
            for &p in &row.prereq {
                assert!(p == -1 || (0..t).contains(&p), "{} prerequisite {p}", TECH_NAMES[i]);
            }
        }
        let tb = tables();
        assert!(tb.units.iter().all(|u| u.required_tech >= -1 && u.required_tech < t));
        assert!(tb.bldgs.iter().all(|b| b.required_advance >= -1 && b.required_advance < t));
        assert_eq!(tb.flavors.len(), 7);
    }
}
